name: login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  table_calendar: ^3.0.9
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  lottie: ^2.6.0
  day_night_switcher: ^0.2.0+1
  concentric_transition: ^1.0.3
  flutter_slider_drawer: ^2.1.3
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.1
  provider: ^6.0.5
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
 

  
  
  http: ^1.1.0
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  animated_react_button: ^0.0.4
lottie: ^3.0.1

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/
     - lib/assets/images/.
     - lib/assets/animation/.
 
     